#!/bin/bash
#
# Enable SSH (dropbear) on a Netgear Orbi RBR50. Listens on your internal interface, not exposed to the internet.
#
# 2020-11-02: In general the system does not allow for persistent changes across reboot. There is though a filesystem
# where you can persist changes: /mnt/bitdefender, that filesystem stores the Orbi's bit defender installation.
#
# This script injects itself into the boot process of the bit defender software and utilizes it's filesystem to store
# software and configuration. 
#
# For more information see: https://github.com/mglantz/ssh-rbr50
# 
# sudo@redhat.com, 2020

INTERNAL_IP=$(ip a l br0|grep -v inet6|grep inet|cut -d' ' -f6|sed 's/\/.*//')

if [ ! -f /sbin/dropbear ]; then
        cd /mnt/bitdefender
        if [ ! -f /mnt/bitdefender/usr/sbin/dropbear ]; then             
                read -p "First time you run this script, it needs to be done manually from a terminal. Press enter." next
                echo "Enter password for the root admin user, which you use to access the system."
                passwd root
                if [ "$?" -eq 0 ]; then
                        cp /etc/passwd /mnt/bitdefender/.passwd.old
                        cp /etc/shadow /mnt/bitdefender/.shadow.old
                        cp /etc/passwd /mnt/bitdefender/.passwd
                        cp /etc/shadow /mnt/bitdefender/.shadow
                fi
                wget --no-check-certificate https://github.com/whiteskin/openwrt-imagebuilder-ipq806x/raw/master/packages/base/dropbear_2015.67-1_ipq806x.ipk
                tar xvzf dropbear_2015.67-1_ipq806x.ipk
                tar xvzf data.tar.gz
                chmod a+rx /mnt/bitdefender/usr/bin/* /mnt/bitdefender/usr/sbin/*
        fi
        if [ ! -f /mnt/bitdefender/.passwd ]; then
                echo "Error: root password not set. Run below and try again:"
                echo "passwd root"
                echo "cp /etc/passwd /mnt/bitdefender/.passwd"
                echo "cp /etc/shadow /mnt/bitdefender/.shadow"
                exit 1
        else
                cp /mnt/bitdefender/.passwd /etc/passwd
                cp /mnt/bitdefender/.shadow /etc/shadow
        fi
        if ! grep start_ssh /mnt/bitdefender/bin/bd >/dev/null; then
                sed -i -e '\/run $BIN_DIR\/bdheartbeatd -start/a \/mnt\/bitdefender\/start_ssh' /mnt/bitdefender/bin/bd
        fi

        if [ ! -d /etc/dropbear ]; then
                mkdir /etc/dropbear
        fi
        cp -Rp /mnt/bitdefender/usr/bin/* /bin/
        cp -Rp /mnt/bitdefender/usr/sbin/* /sbin/
        dropbear -R -p $INTERNAL_IP:22 &
fi

if pidof dropbear >/dev/null; then
        echo "dropbear running"
else
        dropbear -R -p $INTERNAL_IP:22 &
fi
